In [1]:
import os
import numpy as np

# Creating Arrays from Scratch

In [2]:
# create a length - 10 integer array filled with zeros
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
# create a 3x5 floating point array filled with 1s
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# create a 3x5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
#(this is similar to the built - in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# Create an array of five values evenly spaced betwwen 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.40834343, 0.38546808, 0.80686787],
       [0.99902393, 0.5133218 , 0.05233933],
       [0.58393342, 0.79621552, 0.28423676]])

In [18]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 0.6941085 ,  1.17263161,  0.63722976],
       [-0.98543614, -0.93761941,  0.43811552],
       [ 0.80649705, -1.46637083,  0.98952652]])

In [21]:
# Create a 3x3 array of random integers in the interval [0,10)
np.random.randint(0,10,(3,3))

array([[2, 4, 0],
       [0, 9, 2],
       [6, 0, 5]])

In [22]:
# Create indentity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

# Numpy Array Atributes

In [55]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [25]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


# Array Indexing: Accessing Single Elements

In [26]:
# One - dimensional array
x1

array([5, 0, 3, 3, 7, 9])

In [27]:
x1[0]

5

In [28]:
x1[4]

7

In [29]:
x1[-1]

9

In [30]:
# two - dimensional array
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [31]:
x2[0,0]

3

In [32]:
x2[2,-1]

7

# Array Slicing: Accessing Subarrays


In [34]:
# One-dimensional subarrays
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x[:5]

array([0, 1, 2, 3, 4])

In [36]:
x[5:]

array([5, 6, 7, 8, 9])

In [37]:
x[4:7]

array([4, 5, 6])

In [38]:
x[::2]

array([0, 2, 4, 6, 8])

In [39]:
x[1::2]

array([1, 3, 5, 7, 9])

In [40]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [41]:
x[5::-2]

array([5, 3, 1])

In [56]:
# Multidimensional subarrays
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [51]:
x2[:2,:3] # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [46]:
x2[:3,:2] # all rows, two columns

array([[3, 5],
       [7, 6],
       [1, 6]])

In [47]:
x2[:3,::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [57]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [58]:
# Accessing array rows and columns.
x2[:,0]

array([3, 7, 1])

In [61]:
x2[0,:]

array([3, 5, 2, 4])

In [62]:
# Creating copies of arrays
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy

array([[3, 5],
       [7, 6]])

In [63]:
x2_sub_copy[0,0] = 42
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

In [64]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

# Reshaping of arrays

In [66]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Concatenation and Splitting

# Concatenation of arrays

In [67]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [68]:
z = [99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [69]:
grid = np.array([[1,2,3],
                 [4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [75]:
# vstack
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [76]:
# horizontally stack the arrays
y = np.array([[99],
                [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

# Splitting of arrays


In [79]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [80]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
# v.split
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [82]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Introducing Broadcasting


In [83]:
a = np.array([0,1,2])
b = np.array([5,5,5])
a + b

array([5, 6, 7])

In [84]:
a + 5

array([5, 6, 7])

In [86]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [87]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [90]:
a = np.arange(3)
b = np.arange(3)[:,np.newaxis]
print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [91]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Working with Boolean Arrays

In [94]:
x = np.array([[5, 0, 3, 3],
            [7, 9, 3, 5],
            [2, 4, 7, 6]])
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

## Counting entries

In [96]:
# how many values less than 6
np.count_nonzero(x < 6)

8

In [101]:
# how many values less than 6
np.sum(x < 6)

8

In [102]:
# how many values less than 6 in each row
np.sum(x < 6, axis =1)

array([4, 2, 2])

In [103]:
# are there any values greater than 8?
np.any(x>8)

True

In [104]:
# are there any bvalues less than zero
np.any(x<0)

False

In [105]:
# are there all values less than 10
np.all(x>10)

False

In [106]:
# are all values equal to 6?
np.all(x == 6)

False

# Boolean Arrays as Masks

In [107]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [108]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [111]:
x[x<5].reshape(2,-1)

array([[0, 3, 3],
       [3, 2, 4]])